"""Unit tests for release_snapshot.py."""

from __future__ import annotations

import pathlib
import sys
import tempfile
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
import release_snapshot as rs


SAMPLE_OVERVIEW = """\
# Tasks Overview

<!-- GENERATED -->

_Auto-generated by `housekeep.py`. Do not edit manually._

⚪ Open: 1 | 🟢 Closed: 0 | Total: 1
<!-- END GENERATED -->

<!-- BURNUP:START -->

## Burn-up since v0.3.0

| Date | Tasks closed |
|------|-------------:|
| 2026-04-26 | 5 |
<!-- BURNUP:END -->
"""

SAMPLE_KANBAN = """\
# Kanban Board

_Auto-generated by `housekeep.py`. Do not edit manually._

```mermaid
kanban
  Open
    TASK_001["t1"]
```
"""


class TestStripAutogen(unittest.TestCase):
    def test_strips_generated_markers(self):
        out = rs.strip_autogen(SAMPLE_OVERVIEW)
        self.assertNotIn("<!-- GENERATED -->", out)
        self.assertNotIn("<!-- END GENERATED -->", out)

    def test_strips_burnup_markers(self):
        out = rs.strip_autogen(SAMPLE_OVERVIEW)
        self.assertNotIn("<!-- BURNUP:START -->", out)
        self.assertNotIn("<!-- BURNUP:END -->", out)

    def test_strips_autogen_notice(self):
        out = rs.strip_autogen(SAMPLE_OVERVIEW)
        self.assertNotIn("Auto-generated by `housekeep.py`", out)
        out2 = rs.strip_autogen(SAMPLE_KANBAN)
        self.assertNotIn("Auto-generated by `housekeep.py`", out2)

    def test_preserves_visible_content(self):
        out = rs.strip_autogen(SAMPLE_OVERVIEW)
        self.assertIn("# Tasks Overview", out)
        self.assertIn("Open: 1", out)
        self.assertIn("## Burn-up since v0.3.0", out)
        self.assertIn("2026-04-26", out)

    def test_collapses_multiple_blank_lines(self):
        # After stripping, runs of >=3 newlines collapse to a single blank.
        text = "A\n\n\n\nB\n"
        self.assertEqual(rs.strip_autogen(text), "A\n\nB\n")


class TestSnapshotPaths(unittest.TestCase):
    def test_paths_use_version_suffix(self):
        with tempfile.TemporaryDirectory() as t:
            tasks = pathlib.Path(t)
            pairs = rs.snapshot_paths(tasks, "v0.4.0")
            names = sorted(p[1].name for p in pairs)
            self.assertEqual(names,
                             ["EPICS_v0.4.0.md",
                              "KANBAN_v0.4.0.md",
                              "OVERVIEW_v0.4.0.md"])
            for _, dst in pairs:
                self.assertEqual(dst.parent.name, "v0.4.0")
                self.assertEqual(dst.parent.parent.name, "archive")


class TestWriteSnapshots(unittest.TestCase):
    def _setup_tasks_dir(self, td: pathlib.Path) -> pathlib.Path:
        tasks = td / "tasks"
        tasks.mkdir()
        (tasks / "OVERVIEW.md").write_text(SAMPLE_OVERVIEW, encoding="utf-8")
        (tasks / "EPICS.md").write_text(
            "# Epics\n\n_Auto-generated by `housekeep.py`. Do not edit manually._\n\n## Index\n\n_table_\n",
            encoding="utf-8",
        )
        (tasks / "KANBAN.md").write_text(SAMPLE_KANBAN, encoding="utf-8")
        return tasks

    def test_writes_three_snapshots_with_suffix(self):
        with tempfile.TemporaryDirectory() as t:
            td = pathlib.Path(t)
            tasks = self._setup_tasks_dir(td)
            written = rs.write_snapshots(tasks, "v9.9.9")
            archive = tasks / "archive" / "v9.9.9"
            self.assertTrue((archive / "OVERVIEW_v9.9.9.md").exists())
            self.assertTrue((archive / "EPICS_v9.9.9.md").exists())
            self.assertTrue((archive / "KANBAN_v9.9.9.md").exists())
            self.assertEqual(len(written), 3)

    def test_snapshots_are_static(self):
        with tempfile.TemporaryDirectory() as t:
            td = pathlib.Path(t)
            tasks = self._setup_tasks_dir(td)
            rs.write_snapshots(tasks, "v9.9.9")
            content = (tasks / "archive" / "v9.9.9" / "OVERVIEW_v9.9.9.md").read_text(encoding="utf-8")
            self.assertNotIn("<!-- GENERATED -->", content)
            self.assertNotIn("<!-- BURNUP:START -->", content)
            self.assertNotIn("Auto-generated by `housekeep.py`", content)

    def test_does_not_overwrite_existing_release_overview(self):
        # update_task_overview.py writes archive/<version>/OVERVIEW.md
        # with a per-release closed-tasks listing. The new snapshot lives
        # under OVERVIEW_<version>.md, so the legacy file must be left alone.
        with tempfile.TemporaryDirectory() as t:
            td = pathlib.Path(t)
            tasks = self._setup_tasks_dir(td)
            archive = tasks / "archive" / "v9.9.9"
            archive.mkdir(parents=True)
            legacy = archive / "OVERVIEW.md"
            legacy.write_text("LEGACY CONTENT", encoding="utf-8")
            rs.write_snapshots(tasks, "v9.9.9")
            self.assertEqual(legacy.read_text(encoding="utf-8"), "LEGACY CONTENT")

    def test_dry_run_writes_nothing(self):
        with tempfile.TemporaryDirectory() as t:
            td = pathlib.Path(t)
            tasks = self._setup_tasks_dir(td)
            rs.write_snapshots(tasks, "v9.9.9", dry_run=True)
            self.assertFalse((tasks / "archive" / "v9.9.9" / "OVERVIEW_v9.9.9.md").exists())

    def test_missing_source_skipped_silently(self):
        with tempfile.TemporaryDirectory() as t:
            td = pathlib.Path(t)
            tasks = td / "tasks"
            tasks.mkdir()
            # Only EPICS.md exists; OVERVIEW and KANBAN are missing.
            (tasks / "EPICS.md").write_text("# Epics\n", encoding="utf-8")
            written = rs.write_snapshots(tasks, "v9.9.9")
            self.assertEqual(len(written), 1)
            self.assertEqual(written[0].name, "EPICS_v9.9.9.md")


if __name__ == "__main__":
    unittest.main()
