#!/usr/bin/env python3
"""Generate the burn-up section for OVERVIEW.md.

Renders cumulative tasks closed, cumulative epics closed, and cumulative
effort hours (estimated vs actual) since the last git tag. The block is
delimited by `<!-- BURNUP:START -->` / `<!-- BURNUP:END -->` markers and
is regenerated by housekeep.py on every `--apply` pass; idempotent
(no-op when the new block byte-matches the current one).

Module entry points:

    render_block(repo_root: Path) -> str
        Build the BURNUP block content (excluding the markers themselves).

    update_overview_section(overview_path: Path, block: str) -> bool
        Replace (or insert) the BURNUP block in OVERVIEW.md. Returns True
        if the file was actually mutated, False if the new bytes matched
        the existing slice.

CLI: ``python scripts/release_burnup.py [--apply]`` for ad-hoc use.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

BURNUP_START = "<!-- BURNUP:START -->"
BURNUP_END = "<!-- BURNUP:END -->"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
FIELD_RE = re.compile(r"^(\w[\w-]*):\s*(.+)$", re.MULTILINE)

# Canonical six t-shirt sizes → midpoint hours.
TSHIRT_HOURS: dict[str, float] = {
    "XS (<30m)": 0.25,
    "Small (<2h)": 1.0,
    "Medium (2-8h)": 5.0,
    "Large (8-24h)": 16.0,
    "Extra Large (24-40h)": 32.0,
    "XXL (>40h)": 56.0,  # convention, not a true midpoint
}

# Legacy labels (read-only — fade over time as old tasks age out).
LEGACY_MIDPOINTS: dict[str, float] = {
    "Trivial (<30m)": 0.25,
    "Small (1-2h)": 1.0,
    "Small (1-3h)": 1.0,
    "Small (2-4h)": 1.0,
    "Large (>8h)": 16.0,
}


def tshirt_to_hours(label: str | None) -> float | None:
    """Map a frontmatter `effort:` / `effort_actual:` label to midpoint hours.

    Returns None for missing or unrecognised strings.
    """
    if not label:
        return None
    s = str(label).strip()
    if s in TSHIRT_HOURS:
        return TSHIRT_HOURS[s]
    if s in LEGACY_MIDPOINTS:
        return LEGACY_MIDPOINTS[s]
    return None


def _parse_frontmatter(path: Path) -> dict:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    m = FRONTMATTER_RE.match(content)
    if not m:
        return {}
    return dict(FIELD_RE.findall(m.group(1)))


def _git(args: list[str], cwd: Path) -> str:
    """Run a git command and return stdout (stripped).

    Returns the empty string on non-zero exit; callers should handle
    "no tag yet" / "no closures yet" gracefully.
    """
    try:
        r = subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True, check=False,
        )
    except FileNotFoundError:
        return ""
    if r.returncode != 0:
        return ""
    return r.stdout


def _last_tag(repo_root: Path) -> str | None:
    out = _git(["describe", "--tags", "--abbrev=0"], repo_root).strip()
    return out or None


def parse_git_log_for_closures(
    repo_root: Path, tag: str,
    pathspecs: tuple[str, ...] = (
        "docs/developers/tasks/closed/task-*.md",
        "docs/developers/tasks/closed/epic-*.md",
    ),
) -> list[tuple[str, str]]:
    """Return list of (path, date) for every closure commit since `tag`.

    Uses `--diff-filter=A --no-renames` so that:
      - file moves (open/ → closed/, paused/ → closed/, etc.) are reported
        as additions to the closed/ pathspec;
      - paused tasks don't appear (they live in paused/, not closed/);
      - reopen → reclose round-trips show up as multiple entries — the
        caller's dedupe-by-basename keeps the latest.
    """
    args = [
        "log", f"{tag}..HEAD",
        "--diff-filter=A", "--no-renames", "--name-only",
        "--date=short", "--pretty=format:COMMIT %ad",
        "--",
        *pathspecs,
    ]
    raw = _git(args, repo_root)
    return _parse_log_stream(raw)


def _parse_log_stream(raw: str) -> list[tuple[str, str]]:
    """Stream parser for `git log --pretty=format:COMMIT %ad --name-only`.

    Each `COMMIT <date>` sentinel sets the current commit date; every
    following non-empty path until the next sentinel is a closure on
    that date.
    """
    closures: list[tuple[str, str]] = []
    current_date: str | None = None
    for line in raw.splitlines():
        line = line.rstrip()
        if not line:
            continue
        if line.startswith("COMMIT "):
            current_date = line[len("COMMIT "):].strip()
            continue
        if current_date is None:
            continue
        closures.append((line, current_date))
    return closures


def dedupe_by_basename_keep_latest(
    closures: list[dict],
) -> list[dict]:
    """Keep the latest (by date, then by list order) closure per basename.

    Handles the open → active → closed → reopen → reclose round-trip:
    multiple closure events for the same task collapse into the most
    recent one.
    """
    by_name: dict[str, dict] = {}
    for c in closures:
        name = os.path.basename(c["path"])
        existing = by_name.get(name)
        if existing is None or c["date"] >= existing["date"]:
            by_name[name] = c
    return list(by_name.values())


def aggregate_by_day(closures: list[dict]) -> list[dict]:
    """Roll closures up by date; produce a sorted cumulative series.

    Each row: {date, tasks, est_h, actual_h, epics}. Rows include
    cumulative variants too, prefixed `cum_`.
    """
    daily: dict[str, dict[str, float]] = defaultdict(
        lambda: {"tasks": 0, "est_h": 0.0, "actual_h": 0.0, "epics": 0,
                 "actual_h_known": 0}
    )
    for c in closures:
        d = c["date"]
        if c["kind"] == "epic":
            daily[d]["epics"] += 1
        else:
            daily[d]["tasks"] += 1
        if c["effort_h"] is not None:
            daily[d]["est_h"] += c["effort_h"]
        if c["effort_actual_h"] is not None:
            daily[d]["actual_h"] += c["effort_actual_h"]
            daily[d]["actual_h_known"] += 1

    series: list[dict] = []
    cum_tasks = 0
    cum_est = 0.0
    cum_actual = 0.0
    cum_epics = 0
    for d in sorted(daily.keys()):
        row = daily[d]
        cum_tasks += row["tasks"]
        cum_est += row["est_h"]
        cum_actual += row["actual_h"]
        cum_epics += row["epics"]
        series.append({
            "date": d,
            "tasks": int(row["tasks"]),
            "est_h": row["est_h"],
            "actual_h": row["actual_h"],
            "epics": int(row["epics"]),
            "cum_tasks": cum_tasks,
            "cum_est": cum_est,
            "cum_actual": cum_actual,
            "cum_epics": cum_epics,
        })
    return series


def _fmt_hours(h: float) -> str:
    """Pretty-print a midpoint-hour total. Trims trailing .0 for ints."""
    if abs(h - round(h)) < 0.05:
        return f"{int(round(h))}"
    return f"{h:.1f}"


def _short_label(date: str) -> str:
    """Shorten an ISO date (YYYY-MM-DD) to MM-DD for chart x-axis labels.

    Three charts share one row, so the full ISO date no longer fits;
    MM-DD keeps the axis readable while preserving date order. Any
    string that does not match the YYYY-MM-DD shape is returned as-is.
    """
    if len(date) == 10 and date[4] == "-" and date[7] == "-":
        return date[5:]
    return date


def _xychart(title: str, x: list[str], y: list[float]) -> list[str]:
    """Build a Mermaid xychart-beta block for a single line series.

    Falls back to a placeholder note when the series is empty.
    """
    if not x:
        return ["_No data points yet — no closures since the tag._"]
    quoted_x = "[" + ", ".join(f'"{_short_label(d)}"' for d in x) + "]"
    if all(isinstance(v, int) or v == int(v) for v in y):
        line_y = "[" + ", ".join(str(int(v)) for v in y) + "]"
    else:
        line_y = "[" + ", ".join(f"{v:.2f}".rstrip("0").rstrip(".") for v in y) + "]"
    return [
        "```mermaid",
        "xychart-beta",
        f'    title "{title}"',
        f"    x-axis {quoted_x}",
        f"    line {line_y}",
        "```",
    ]


def _xychart_two_series(title: str, x: list[str],
                        y1: list[float], y2: list[float]) -> list[str]:
    """Two stacked lines on one xychart-beta. The chart's title carries
    the series identity in case the color palette is not honored."""
    if not x:
        return ["_No data points yet — no closures since the tag._"]
    quoted_x = "[" + ", ".join(f'"{_short_label(d)}"' for d in x) + "]"

    def _fmt(vals: list[float]) -> str:
        return "[" + ", ".join(f"{v:.2f}".rstrip("0").rstrip(".") for v in vals) + "]"

    return [
        "```mermaid",
        "xychart-beta",
        f'    title "{title}"',
        f"    x-axis {quoted_x}",
        f"    line {_fmt(y1)}",
        f"    line {_fmt(y2)}",
        "```",
    ]


def render_block(repo_root: Path) -> str:
    """Render the body of the BURNUP block (between the markers, exclusive).

    Returns a string that begins with a newline — the caller wraps it
    with the markers and a trailing newline.
    """
    tag = _last_tag(repo_root)
    if tag is None:
        return ('\n<a id="burn-up"></a>\n\n'
                "_No git tag found yet — burn-up chart needs a release"
                " tag to anchor on._\n")

    raw = parse_git_log_for_closures(repo_root, tag)
    closures: list[dict] = []
    for path, date in raw:
        full = repo_root / path
        fm = _parse_frontmatter(full) if full.exists() else {}
        kind = "epic" if os.path.basename(path).startswith("epic-") else "task"
        closures.append({
            "path": path,
            "date": date,
            "kind": kind,
            "effort_h": tshirt_to_hours(fm.get("effort")),
            "effort_actual_h": tshirt_to_hours(fm.get("effort_actual")),
        })

    closures = dedupe_by_basename_keep_latest(closures)
    series = aggregate_by_day(closures)

    # Stable HTML anchor — the heading slug ("burn-up-since-v0-3-0")
    # changes with every release, but the Jump-to index points at a
    # fixed `#burn-up`.
    lines: list[str] = ["", '<a id="burn-up"></a>', "",
                        f"## Burn-up since {tag}", ""]

    if not series:
        lines += [f"_No tasks or epics closed since {tag} yet._", ""]
        return "\n" + "\n".join(lines)

    x = [r["date"] for r in series]
    cum_tasks = [r["cum_tasks"] for r in series]
    cum_epics = [r["cum_epics"] for r in series]
    cum_est = [r["cum_est"] for r in series]
    cum_actual = [r["cum_actual"] for r in series]

    # Charts first — three side-by-side cells in a markdown table.
    # Mermaid renders inside table cells on GitHub today; if it ever
    # stops, the fallback is three stacked sections. X-axis labels are
    # shortened to MM-DD because the full ISO date no longer fits when
    # three charts share a row.
    lines += [
        "<table><tr><td>",
        "",
    ] + _xychart("Cumulative tasks closed", x, cum_tasks) + [
        "",
        "</td><td>",
        "",
    ] + _xychart("Cumulative epics closed", x, cum_epics) + [
        "",
        "</td><td>",
        "",
    ] + _xychart_two_series(
        "Cumulative effort hours — green: estimate, blue: actual",
        x, cum_est, cum_actual,
    ) + [
        "",
        "</td></tr></table>",
        "",
        "_Legend: green line = estimate (midpoint hours from `effort:`);"
        " blue line = actual (midpoint hours from `effort_actual:`)._",
        "",
    ]

    # Numeric table follows the charts — for readers who want the raw
    # daily and cumulative values behind the lines.
    lines += [
        "| Date | Tasks closed | Cum. tasks | Est. h | Cum. est. h |"
        " Actual h | Cum. actual h | Epics closed | Cum. epics |",
        "|------|-------------:|-----------:|-------:|------------:|"
        "---------:|--------------:|-------------:|-----------:|",
    ]
    for row in series:
        lines.append(
            f"| {row['date']} | {row['tasks']} | {row['cum_tasks']}"
            f" | {_fmt_hours(row['est_h'])} | {_fmt_hours(row['cum_est'])}"
            f" | {_fmt_hours(row['actual_h'])} | {_fmt_hours(row['cum_actual'])}"
            f" | {row['epics']} | {row['cum_epics']} |"
        )
    # Blank line so the BURNUP:END marker doesn't fuse with the last
    # table row.
    lines.append("")

    return "\n" + "\n".join(lines)


def _strip_burnup_block(content: str) -> str:
    """Return `content` with any existing BURNUP block removed.

    Used both by update_overview_section (to relocate the block) and by
    remove_overview_section (when the visualization is disabled).
    """
    start = content.find(BURNUP_START)
    end = content.find(BURNUP_END)
    if start == -1 or end == -1 or end <= start:
        return content
    block_end = end + len(BURNUP_END)
    # Eat one trailing newline so we don't accumulate blank lines on
    # repeated regenerations.
    if block_end < len(content) and content[block_end] == "\n":
        block_end += 1
    return content[:start].rstrip() + "\n" + content[block_end:].lstrip("\n")


def remove_overview_section(overview_path: Path) -> bool:
    """Remove the BURNUP block from OVERVIEW.md. Idempotent.

    Called by housekeep when `visualizations.burnup.enabled` is false so
    that toggling the flag off cleans up the previously-rendered block.
    Returns True if the file was mutated, False if no BURNUP block was
    present (the no-op case).
    """
    if not overview_path.exists():
        return False
    content = overview_path.read_text(encoding="utf-8")
    stripped = _strip_burnup_block(content)
    if stripped == content:
        return False
    overview_path.write_text(stripped, encoding="utf-8")
    return True


def update_overview_section(overview_path: Path, block: str) -> bool:
    """Insert/replace the BURNUP block in OVERVIEW.md. Idempotent.

    Returns True if the file was mutated, False if the new bytes match
    the existing slice (true idempotency — `housekeep --apply` does
    not touch the file on idle days).
    """
    if not overview_path.exists():
        return False
    content = overview_path.read_text(encoding="utf-8")

    new_section = f"{BURNUP_START}{block}{BURNUP_END}\n"

    # Strip any existing BURNUP block first, then insert fresh at the
    # canonical position. This is what relocates a previously-placed
    # block (above the H1, or below the task tables in older revisions)
    # to the current target.
    stripped = _strip_burnup_block(content)

    # Insert directly after the HEADER block (counts line + Jump-to index)
    # so the at-a-glance metadata stays right under the H1 and the burn-up
    # charts sit between the header and the task tables. Fall back to
    # inserting after the H1 (when a HEADER block hasn't been written yet),
    # then to prepending, so the function never silently no-ops.
    header_end_marker = "<!-- END HEADER -->"
    header_end = stripped.find(header_end_marker)
    h1_match = re.search(r"^#\s+.+$", stripped, flags=re.MULTILINE)
    if header_end != -1:
        insert_at = header_end + len(header_end_marker)
        prefix = stripped[:insert_at].rstrip() + "\n\n"
        suffix = stripped[insert_at:].lstrip("\n")
        new_content = prefix + new_section + "\n" + suffix
    elif h1_match is not None:
        insert_at = h1_match.end()
        prefix = stripped[:insert_at].rstrip() + "\n\n"
        suffix = stripped[insert_at:].lstrip("\n")
        new_content = prefix + new_section + "\n" + suffix
    else:
        new_content = new_section + "\n" + stripped

    if new_content == content:
        return False
    overview_path.write_text(new_content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render the BURNUP section into OVERVIEW.md."
    )
    parser.add_argument("--apply", action="store_true",
                        help="Write the section to OVERVIEW.md "
                             "(default is print to stdout).")
    parser.add_argument("--repo-root", type=Path, default=None,
                        help="Repo root (default: cwd).")
    args = parser.parse_args(argv)

    repo_root = args.repo_root or Path.cwd()
    block = render_block(repo_root)

    if args.apply:
        overview = repo_root / "docs" / "developers" / "tasks" / "OVERVIEW.md"
        changed = update_overview_section(overview, block)
        print("release_burnup: updated." if changed
              else "release_burnup: no change.")
        return 0

    sys.stdout.write(BURNUP_START + block + BURNUP_END + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
