#!/usr/bin/env python3
"""Snapshot OVERVIEW / EPICS / KANBAN into `archive/<version>/` on release.

When a release is cut, the live `docs/developers/tasks/{OVERVIEW,EPICS,KANBAN}.md`
keep evolving. This helper freezes the post-archive state into the
per-release `archive/<version>/` folder under the names:

    OVERVIEW_<version>.md
    EPICS_<version>.md
    KANBAN_<version>.md

The snapshots are static — they are demoted from auto-generated documents
to frozen artifacts. The auto-generation markers and "do not edit
manually" notices are stripped on the way in so `housekeep.py` will not
touch them on later runs.

Usage:
    python scripts/release_snapshot.py vX.Y.Z         # write snapshots
    python scripts/release_snapshot.py vX.Y.Z --dry-run

The existing `archive/<version>/OVERVIEW.md` (the per-release
"tasks closed in this release" listing generated by
`update_task_overview.py`) is **not** touched — the new snapshots live
beside it under their suffixed names.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Sources to snapshot (relative to TASKS_DIR).
SOURCES = ("OVERVIEW.md", "EPICS.md", "KANBAN.md")

# Lines / blocks stripped on the way in. The chart bodies wrapped by the
# BURNUP markers stay — they are valid Markdown / Mermaid that the reader
# is here for. Only the comment delimiters and "auto-generated" boilerplate
# are removed.
_AUTOGEN_NOTICE_RE = re.compile(
    r"^_Auto-generated by `housekeep\.py`\.\s*Do not edit manually\._\s*$",
    re.MULTILINE,
)
_GENERATED_MARKER_RE = re.compile(
    r"^<!--\s*(?:END\s+)?GENERATED\s*-->\s*$", re.MULTILINE,
)
_BURNUP_MARKER_RE = re.compile(
    r"^<!--\s*BURNUP:(?:START|END)\s*-->\s*$", re.MULTILINE,
)


def strip_autogen(content: str) -> str:
    """Remove auto-generation markers and notices from a generated overview.

    The visible body (tables, charts, sections) is preserved verbatim.
    Multiple consecutive blank lines that result from stripping are
    collapsed to a single blank line so the snapshot reads cleanly.
    """
    out = _AUTOGEN_NOTICE_RE.sub("", content)
    out = _GENERATED_MARKER_RE.sub("", out)
    out = _BURNUP_MARKER_RE.sub("", out)
    # Collapse runs of >=3 newlines down to 2 (one blank line max).
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out.lstrip("\n")


def snapshot_paths(tasks_dir: Path, version: str) -> list[tuple[Path, Path]]:
    """Return [(source, destination)] pairs for the snapshot."""
    archive_dir = tasks_dir / "archive" / version
    return [
        (tasks_dir / src, archive_dir / f"{Path(src).stem}_{version}.md")
        for src in SOURCES
    ]


def write_snapshots(tasks_dir: Path, version: str, *, dry_run: bool = False) -> list[Path]:
    """Write snapshot files. Returns the destination paths that were written.

    Skips silently when a source is missing (renderer not run yet).
    """
    written: list[Path] = []
    for src, dst in snapshot_paths(tasks_dir, version):
        if not src.exists():
            print(f"release_snapshot: SKIP (source missing): {src}",
                  file=sys.stderr)
            continue
        content = src.read_text(encoding="utf-8")
        snapshot = strip_autogen(content)
        if dry_run:
            print(f"release_snapshot: WOULD WRITE: {dst}")
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(snapshot, encoding="utf-8")
        print(f"release_snapshot: WROTE: {dst}")
        written.append(dst)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Snapshot OVERVIEW / EPICS / KANBAN into archive/<version>/."
    )
    parser.add_argument("version", help="Release version (e.g. v0.4.0)")
    parser.add_argument("--tasks-dir", type=Path,
                        default=Path("docs/developers/tasks"),
                        help="Path to the tasks/ root (default: docs/developers/tasks).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be written, don't write.")
    args = parser.parse_args(argv)

    if not re.fullmatch(r"v\d+\.\d+\.\d+", args.version):
        print(f"release_snapshot: invalid version format: {args.version}"
              " (expected vX.Y.Z)", file=sys.stderr)
        return 2

    write_snapshots(args.tasks_dir, args.version, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
